# Generated by Django 4.2.10 on 2024-03-04 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geekhaven_blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPosts",
            new_name="BlogPost",
        ),
    ]
