# Generated by Django 4.2.10 on 2024-03-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekhaven_blog', '0003_blogpost_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_content',
            field=models.TextField(default=''),
        ),
    ]
