# Generated by Django 4.2.10 on 2024-03-06 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geekhaven_blog", "0008_blogcomments"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_body", models.TextField(default="")),
                ("comment_approved", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "comment_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_commenter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment_which_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to="geekhaven_blog.blogpost",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BlogComments",
        ),
    ]
