# Generated by Django 4.2.10 on 2024-03-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geekhaven_blog", "0009_blogcomment_delete_blogcomments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcomment",
            options={"ordering": ["creation_date"]},
        ),
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-creation_date"]},
        ),
    ]
