# Generated by Django 4.2.10 on 2024-03-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekhaven_blog', '0010_alter_blogcomment_options_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='url_slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
