# Generated by Django 4.2.10 on 2024-03-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geekhaven_blog", "0011_alter_blogpost_url_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
