# Generated by Django 4.2.10 on 2024-03-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geekhaven_blog", "0012_searchbar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchBar",
        ),
    ]
