# Generated by Django 4.2.10 on 2024-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geekhaven_blog", "0015_cosplaysubmission_submission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cosplaysubmission",
            name="approval_state",
            field=models.BooleanField(default=False),
        ),
    ]
