# Generated by Django 4.2.10 on 2024-04-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geekhaven_blog", "0017_remove_cosplaysubmission_submission_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CosplaySubmission",
        ),
    ]
